/* Tokyonight Night Theme */
static char background[]    = "#1a1b26";   /* bg */
static char foreground[]    = "#c0caf5";   /* fg */
static char selbackground[] = "#1a1b26";   /* selbg */
static char selforeground[] = "#7aa2f7";   /* selfg */
static char color0[]        = "#15161e";   /* black */
static char color1[]        = "#f7768e";   /* red */
static char color2[]        = "#9ece6a";   /* green */
static char color3[]        = "#e0af68";   /* yellow */
static char color4[]        = "#7aa2f7";   /* blue */
static char color5[]        = "#bb9af7";   /* magenta */
static char color6[]        = "#7dcfff";   /* cyan */
static char color7[]        = "#a9b1d6";   /* white */
static char color8[]        = "#414868";   /* black alt */
static char color9[]        = "#f7768e";   /* red alt */
static char color10[]       = "#9ece6a";   /* green alt */
static char color11[]       = "#e0af68";   /* yellow alt */
static char color12[]       = "#7aa2f7";   /* blue alt */
static char color13[]       = "#bb9af7";   /* magenta alt */
static char color14[]       = "#7dcfff";   /* cyan alt */
static char color15[]       = "#c0caf5";   /* white alt */
